### ISSUE TITLE
ATLAS Review - Scripts and notebooks

### ISSUE THREAD

**Issue by rmanzanas** [IPCC-WG1/Atlas#33] opened 2021-01-08 10:56 UTC
First of all, let me highlight that the scripts and notebooks provided are extremely useful to promote transparency, reproducibility and re-usability! That said, I'd like to make a comment on this regard. My view differs from other previous review comments, which suggest to store all the scripts/notebooks into a unique, dedicated directory. Instead, I find useful to include a "scripts" and a "notebook" directory within each main directory (e.g. "aggregated-datasets", "reference-regions"), since it'll be easier for a user to find what he/she's looking for. Following from this, I wonder if keeping the current "scripts" and "notebooks" directories (which are rather empty), at the root level, makes much sense. Perhaps it could be appropriate to create a new "figs" directory at this level, and include there the scripts/notebooks which allow to reproduce the key figures of the Atlas chapter.

**Comment by jesusff** [comment] 2021-06-15 10:18
Thank you for the review. This is related to #22, so I close the issue here and mark it as Duplicate of #22 to follow the discussion there.

There is a new structure (f494de8) that mainly follows this suggestion. The suggested `figs` directory at root level is currently called `reproducibility` to emphasize the idea of reproducing the key figures in the Atlas chapter.

**Comment by jesusff** [comment] 2021-06-15 10:21
Duplicate of #22

**Closed as completed** 2021-06-15 10:22 UTC
Labels: review
