### ISSUE TITLE
The tabs of the region-specific panel do not show the graphs.

### ISSUE THREAD

**Issue by Zerosimi** [IPCC-WG1/Atlas#95] opened 2024-07-01 12:48 UTC
**Description of the problem**

The region-specific panel, which opens after clicking on a region, does not work. It shows: "Something went wrong" https://interactive-atlas.ipcc.ch/permalink/bexI7fiJ. It comes up for every variable/region/tab I checked and for every device I tested (different personal computers with different OS).

**To Reproduce**

1. Open the Interactive Atlas
2. Click on a region
3. It pops up with the error

**Expected behavior**

It should show some kinds of graphs (over time, scatter plots and so on)

**Screenshots**

<img width="1438" alt="Screenshot 2024-07-01 at 15 45 41" src="https://github.com/IPCC-WG1/Atlas/assets/81266305/8f16de76-5da9-4b14-b7ee-1be6163aacfe">

**Desktop**

 - OS: MacOS (but colleagues with Windows have same issue)
 - Browser: Chrome

**Comment by jesusff** [comment] 2024-07-08 10:02
Thank you for reporting, @Zerosimi 

The problem is now fixed. Please, reopen the issue if you still find something broken.

**Closed as completed by jesusff** 2024-07-08 10:02 UTC
