### ISSUE TITLE
Empty surface ocean pH (value) .nc files 

### ISSUE THREAD

**Issue by mokhodge** [IPCC-WG1/Atlas#73] opened 2021-12-06 14:14 UTC
- Before reporting a problem, please check at the following link that the problem has not been reported yet: https://github.com/IPCC-WG1/Atlas/issues?q=label%3Aerrata

**Description of the problem**

Downloading the .nc file for surface ocean pH values (instead of change) returns an empty file 

**To Reproduce**

Write below the steps to reproduce the problem:

1. Dataset: Model projection = CMIP6
2. Variable: pH at surface 
3. Quantity & Scenario: Value (pH), Period = Medium Term and Scenario = SSP5-8.5

https://interactive-atlas.ipcc.ch/permalink/OTv1mWRN

**Expected behavior**

I would expect this to return a populated .nc file

**Screenshots**

**Desktop (please complete the following information):**

Happens in both Chrome and Firefox

**Additional context**

**Comment by jesusff** [comment] 2021-12-07 06:43
Duplicate of #71

**Closed as completed by jesusff** 2021-12-07 06:43 UTC
Labels: duplicate, problem, IA_Fixed_Dec2021, IA
